version: '3'
services:
  redis:
    image: redis:4.0.11
    volumes:
      - redis-data:/data
  minutes-server:
    build:
      context: .
    environment:
      - PORT0=8080
      - DBHOST=redis
      - DBPORT=6379
    ports:
      - "8080:8080"
    depends_on:
      - redis

volumes:
  redis-data: